apiVersion: v1
kind: Service
metadata:
  name: app-backend-svc
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: backend
    app.kubernetes.io/environment: prod
spec:
  type: NodePort
  selector:
    app: app-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
